apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realworld-backend
  template:
    metadata:
      labels:
        app: realworld-backend
    spec:
      containers:
      - name: realworld-backend
        image: pierresimt/backend
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 3000
        env:
        - name: MONGODB_URI
          value: 'mongodb://mongo-service:27017/conduit?authSource=admin'
        - name: NODE_ENV
          value: 'production'
        - name: SECRET
          value: 'secret'
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: realworld-backend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: realworld-backend
