apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realworld-frontend
  template:
    metadata:
      labels:
        app: realworld-frontend
    spec:
      containers:
      - name: realworld-frontend
        image: pierresimt/frontend
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: realworld-frontend
spec:
    type: NodePort
    ports:
    - port: 5000
      targetPort: 5000
    selector:
      app: realworld-frontend
        